#!/bin/bash

. /Users/chyhfj/Development/MiraSDK/Products/android/android-toolchain-arm/sysroot/usr/share/GNUstep/Makefiles/GNUstep.sh

make debug=yes
make install debug=yes

pushd /Users/chyhfj/Development/MiraSDK/Products/android/android-toolchain-arm/sysroot/usr/lib

mv libgnustep-base.so.1.24.6 libgnustep-base.so
rm libgnustep-base.so.1.24
popd