#!/bin/bash

. /Users/chyhfj/Development/MiraSDK/Products/android/android-toolchain-arm/sysroot/usr/share/GNUstep/Makefiles/GNUstep.sh

LIBS="-lgnustl_shared" ./configure --prefix=/Users/chyhfj/Development/MiraSDK/Products/android/android-toolchain-arm/sysroot/usr --host="arm-linux-androideabi" --enable-nxconstantstring --enable-pass-arguments -disable-xslt --disable-tls --with-xml-prefix=/Users/chyhfj/Development/MiraSDK/Products/android/android-toolchain-arm/sysroot/usr --disable-openssl