#!/bin/bash

. /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/Android18.sdk/usr/share/GNUstep/Makefiles/GNUstep.sh

make debug=yes
make install debug=yes

pushd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/Android18.sdk/usr/lib

mv libgnustep-base.so.1.24.6 libgnustep-base.so
rm libgnustep-base.so.1.24
popd